---

- name: "Ensure service group '{{ mariadb_server__group_runas }}' is present"
  group:
    name:   '{{ mariadb_server__group_runas }}'
    system: yes
    state:  present
  notify: [ 'restart-mariadb' ]

- name: "Ensure service user '{{ mariadb_server__user_runas }}' is present"
  user:
    name:       '{{ mariadb_server__user_runas }}'
    group:      '{{ mariadb_server__group_runas }}'
    shell:      /bin/false
    home:       '{{ mariadb_server__datadir }}'
    createhome: no
    system:     yes
    state:      present
  notify: [ 'restart-mariadb' ]

- name: Ensure configuration directory exists
  file:
    path:  '{{ mariadb_server__configuration_dir }}'
    owner: root
    group: root
    mode:  0755
    state: directory

- name: Ensure configuration included directory exists
  file:
    name:  '{{ mariadb_server__include_configuration_dir }}'
    owner: root
    group: root
    mode:  0755
    state: directory

- name: Ensure log directory exists
  file:
    name:  '{{ mariadb_server__log_dir }}'
    owner: '{{ mariadb_server__user_runas }}'
    group: '{{ mariadb_server__log_dir_group|d(mariadb_server__group_runas) }}'
    mode:  "{{ mariadb_server__log_dir_mode|d('0755') }}"
    state: directory

- name: Create MariaDB configuration
  template:
    src:   my.cnf.j2
    dest:  '{{ mariadb_server__configuration_file }}'
    owner: root
    group: root
    mode:  0644
  notify: ['restart-mariadb']

- name: List installed configuration files
  find:
    paths:     '{{ mariadb_server__include_configuration_dir }}'
    file_type: file
  register: _mariadb__installed_config_files
  check_mode: no

- name: List defined templates files
  set_fact:
    _mariadb__template_config_files: "{{ _mariadb__template_config_files|d([])|union([ item|basename|replace(\'.j2\', \'\') ]) }}"
  with_fileglob:
    - ../templates/conf.d/*.j2

- name: Remove unknown configuration files
  file:
    path:  '{{ item.path }}'
    state: absent
  with_items: '{{ _mariadb__installed_config_files.files }}'
  when: item.path|basename not in _mariadb__template_config_files
  notify: ['restart-mariadb']

- name: Create MariaDB configuration files
  template:
    src:   '{{ item }}'
    dest:  "{{ mariadb_server__include_configuration_dir }}/{{ item|basename|replace('.j2','') }}"
    owner: root
    group: root
    mode:  0644
  with_fileglob:
    - ../templates/conf.d/*.j2
  notify: ['restart-mariadb']
