---

- name: Create custom fact directory
  file:
    path: "{{ facts__dir|d('/etc/ansible/facts.d') }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: ['mariadb-server', 'mariadb-server-facts']

- name: Insert custom fact file
  template:
    src: mariadb.fact.py.j2
    dest: "{{ facts__dir|d('/etc/ansible/facts.d') }}/mariadb.fact"
    owner: root
    group: root
    mode: 0755
  tags: ['mariadb-server', 'mariadb-server-facts']
