---

- name: Add MariaDB repository GPG key to apt keyring
  apt_key:
    id:        '{{ item.id }}'
    keyserver: '{{ item.keyserver }}'
    state:     "{{ item.state|d('present') }}"
  with_items: '{{ mariadb_server__gpg_keys[ansible_lsb.id] if (ansible_lsb.id is defined and ansible_lsb.id in mariadb_server__gpg_keys) else (
                    mariadb_server__gpg_keys[ansible_distribution] if (ansible_distribution is defined and ansible_distribution in mariadb_server__gpg_keys) else (
                      mariadb_server__gpg_keys[ansible_os_family] if (ansible_os_family in mariadb_server__gpg_keys) else ([])
                    )
              ) }}'
  register: _mariadb_server__apt_key
  ignore_errors: '{{ httpproxy is defined }}'
  tags: ['mariadb-server', 'mariadb-server-install']

- name: Add repository APT key using http proxy
  command: apt-key adv --keyserver-options "http-proxy={{ httpproxy }}" --keyserver '{{ item.keyserver }}' --recv-keys '{{ item.id }}'
  with_items: '{{ mariadb_server__gpg_keys[ansible_lsb.id] if (ansible_lsb.id is defined and ansible_lsb.id in mariadb_server__gpg_keys) else (
                    mariadb_server__gpg_keys[ansible_distribution] if (ansible_distribution is defined and ansible_distribution in mariadb_server__gpg_keys) else (
                      mariadb_server__gpg_keys[ansible_os_family] if (ansible_os_family in mariadb_server__gpg_keys) else ([])
                    )
                  ) }}'
  when: _mariadb_server__apt_key is failed and httpproxy is defined
  tags: ['mariadb-server', 'mariadb-server-install']

- name: Add APT repository
  apt_repository:
    filename: mariadb
    repo:     'deb [arch=amd64,i386,ppc64el] {{ mariadb_server__repository_base_url }} {{ ansible_distribution_release|lower }} main'
    state:    present
  tags: ['mariadb-server', 'mariadb-server-install']

- name: Install server package
  apt:
    name:  '{{ item }}'
    state: present
  with_items: '{{ mariadb_server__packages_names }}'
  register: _mariadb_server__packages
  tags: ['mariadb-server', 'mariadb-server-install']
