---

- name: Remove conflicting packages
  package:
    name:  '{{ item }}'
    state: absent
  with_items: '{{ mariadb_server__conflict_packages_names }}'

- name: Install required packages
  package:
    name:  '{{ item }}'
    state: present
  with_items: '{{ mariadb_server__required_packages_names }}'

- include_tasks: '{{ file_item }}'
  with_first_found:
    - files:
        - 'install-{{ ansible_distribution }}-{{ ansible_architecture }}.yml'
        - 'install-{{ ansible_distribution }}.yml'
        - 'install-{{ ansible_os_family }}-{{ ansible_architecture }}.yml'
        - 'install-{{ ansible_os_family }}.yml'
  loop_control:
    loop_var: file_item

- name: Wait for the server to init its database
  pause:
    seconds: 10
    prompt: DONT KILL THIS PAUSE
  when: _mariadb_server__packages is defined
      and _mariadb_server__packages is changed
      and not ansible_check_mode

- name: Stop the database to allow full configuration
  service:
    name:  '{{ mariadb_server__service_name }}'
    state: stopped
  when: _mariadb_server__packages is defined and _mariadb_server__packages is changed
