---
# tasks file for mariadb-server

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Importing initialization tasks
  import_tasks: init.yml
  tags: ['always']

- name: Importing install tasks
  import_tasks: install.yml
  tags: ['mariadb-server', 'mariadb-server-install']

- name: Importing configuration tasks
  import_tasks: configure.yml
  tags: ['mariadb-server', 'mariadb-server-configure']

- name: Importing database initializing tasks
  import_tasks: initdb.yml
  tags: ['mariadb-server', 'mariadb-server-initdb']

- name: Importing service tasks
  import_tasks: service.yml
  tags: ['mariadb-server', 'mariadb-server-service']

- meta: flush_handlers
  tags: ['always']

- include_tasks: hardening.yml
  when: mariadb_server__service_enabled|bool
  tags: ['mariadb-server', 'mariadb-server-hardening']

- include_tasks: databases.yml
  when: mariadb_server__service_enabled|bool
  tags: ['mariadb-server', 'mariadb-server-databases']

- include_tasks: users.yml
  when: mariadb_server__service_enabled|bool
  tags: ['mariadb-server', 'mariadb-server-users']

- name: Optionally importing monitoring tasks
  include_tasks: 'monitoring/{{ mariadb_server__monitoring }}.yml'
  when: mariadb_server__monitoring is defined
  tags: ['mariadb-server', 'mariadb-server-monitoring']

- name: Optionally importing facts tasks
  include_tasks: facts.yml
  when: mariadb_server__facts|bool
  tags: ['mariadb-server', 'mariadb-server-facts']
