---
# tasks file for mariadb-server

- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      skip: true
  tags: ['always']

- import_tasks: init.yml
  tags: ['always']

- import_tasks: install.yml
  tags: ['mariadb-server', 'mariadb-server-install']

- import_tasks: configure.yml
  tags: ['mariadb-server', 'mariadb-server-configure']

- import_tasks: service.yml
  tags: ['mariadb-server', 'mariadb-server-service']

- meta: flush_handlers
  tags: ['always']

- import_tasks: databases.yml
  tags: ['mariadb-server', 'mariadb-server-databases']

- import_tasks: users.yml
  tags: ['mariadb-server', 'mariadb-server-users']
