---

- name: Ensure MariaDB is running
  service:
    name:  '{{ mariadb_server__service_name }}'
    state: started
  tags: ['mariadb-server', 'mariadb-server-users']

- name: Secure root user
  mysql_user:
    name:              '{{ mariadb_server__root_login }}'
    password:          '{{ mariadb_server__root_password }}'
    host_all:          yes
    login_unix_socket: '{{ mariadb_server__socket_file }}'
    login_user:        '{{ mariadb_server__root_login }}'
    login_password:    '{{ mariadb_server__root_password }}'
    state:             'present'
  when: mariadb_server__root_password is defined
  register: _mariadb_server__users_root
  ignore_errors: True
  no_log: yes
  tags: ['mariadb-server', 'mariadb-server-users']

# Temporary because ansible do not hide password
- name: Extract error message from root user setup
  fail:
    msg: "{{ _mariadb_server__users_root.msg }}"
  when: _mariadb_server__users_root is failed
  tags: ['mariadb-server', 'mariadb-server-users']

- name: Setup MariaDB users
  mysql_user:
    name:              '{{ item.user }}'
    password:          '{{ item.password|d(omit) }}'
    host:              '{{ item.host|d(omit) }}'
    encrypted:         '{{ item.encrypted|d(omit) }}'
    priv:              '{{ item.priv|d(omit) }}'
    login_unix_socket: '{{ mariadb_server__socket_file }}'
    login_user:        '{{ mariadb_server__root_login }}'
    login_password:    '{{ mariadb_server__root_password|d(omit) }}'
    state:             "{{ item.state|d('present') }}"
  with_items: '{{ mariadb_server__users }}'
  register: _mariadb_server__users
  ignore_errors: True
  no_log: yes
  tags: ['mariadb-server', 'mariadb-server-users']

# Temporary because ansible do not hide password
- name: Extract error message from users setup
  fail:
    msg: "{{ _mariadb_server__users.results|reject('success')|map(attribute='msg')|list|join(' ') }}"
  when: _mariadb_server__users is failed
  tags: ['mariadb-server', 'mariadb-server-users']
