---

- name: Check configuration prerequisites
  assert:
    that:
      - mariadb_server__credential_cnf is defined
      - mariadb_server__credential_cnf.path is defined
      - mariadb_server__credential_cnf.state|d('present') in ['present', 'absent']
    msg: >
      mariadb_server__credential_cnf must be defined with specifications,
      mariadb_server__credential_cnf.path must contains the path of thefile
  tags: ['always']

# Ensure required folder before the full php role is applied

- name: Ensure parent directory exists
  file:
    path: '{{ mariadb_server__credential_cnf.path|dirname }}'
    state: directory
  tags: ['mariadb-server', 'mariadb-server-configure', 'mariadb-server-credential']

- name: Install credential configuration file
  template:
    src: credential.cnf.j2
    dest: '{{ mariadb_server__credential_cnf.path }}'
    owner: root
    group: root
    mode: 0644
  when: mariadb_server__credential_cnf.state|d('present') == 'present'
  tags: ['mariadb-server', 'mariadb-server-configure', 'mariadb-server-credential']

- name: Remove credential configuration file
  file:
    path: '{{ mariadb_server__credential_cnf.path }}'
    state: absent
  when: mariadb_server__credential_cnf.state|d('present') != 'present'
  tags: ['mariadb-server', 'mariadb-server-configure', 'mariadb-server-credential']
