---
# handlers file for mariadb-server

- name: restart-mariadb-daemon
  service:
    name:  '{{ mariadb_server__service_name }}'
    state: restarted
  when: mariadb_server__service_enabled|bool and mariadb_server__service_restartable|bool
  listen: restart-mariadb-server

- name: mark-mariadb-daemon-to-restart
  file:
    path:  '{{ mariadb_server__service_restart_stamp_file }}'
    state: touch
  when: mariadb_server__service_enabled|bool and not mariadb_server__service_restartable|bool
  listen: restart-mariadb-server
